# Generated by Django 2.0.2 on 2018-02-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('crawled_date', models.DateTimeField(verbose_name='date crawled')),
                ('title', models.CharField(max_length=200)),
                ('body_text', models.TextField()),
            ],
        ),
    ]
